### ISSUE TITLE
Private IP matching is a bit naive

### ISSUE THREAD

**Issue by Hanserfaust** [Miserlou/django-easy-timezones#10]
Nice project and all. Im using it in production, but i found a glitch in your code related to detecting if the IP is in the private range. I think it only concerns IPs starting with 172. A correct match should be 172.16.0.0 and all IPs up to 172.31.255.255.

Read up on
http://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces

cheers!
/H

**Comment by Miserlou** [comment]
Better loopback detection has landed in 0.6.0
