### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by dtamez** [Miserlou/django-easy-timezones#12]
Running pip install django-easy-timezones is resulting in the following error:
Downloading/unpacking django-easy-timezones
  Running setup.py (path:/tmp/pip-build-qTh9qM/django-easy-timezones/setup.py) egg_info for package django-easy-timezones
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-qTh9qM/django-easy-timezones/setup.py", line 12, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-qTh9qM/django-easy-timezones/requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-qTh9qM/django-easy-timezones/setup.py", line 12, in <module>

    with open(os.path.join(os.path.dirname(__file__), 'requirements.txt')) as f:

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-qTh9qM/django-easy-timezones/requirements.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-qTh9qM/django-easy-timezones
Storing debug log for failure in /root/.pip/pip.log

**Comment by Miserlou** [comment]
Tx for reporting!
