### ISSUE TITLE
Detected timezone not saved in session

### ISSUE THREAD

**Issue by aaj** [Miserlou/django-easy-timezones#8]
Hi

I'm reading through the code, which isn't even that big, but I can't find where the detected tz is saved into the session. I've been running some tests and it looks like it isn't saved. I find it confusing that the middleware is using request.session.get('django_timezone'), but never setting a key with that name. Or am I just dumb and missing something?

I could use a signal, but that sends me the user's instance, not the request. Also, I need to do stuff with that session value in a view, and I'm not really sure if django signals are synchronous.

Would it be possible to "fix" this? Or is this the intended behavior?

**Comment by lucas03** [comment]
since nobody replied to you, I just put here my guess. I think timezone.activate() creates session. Did you try to follow that method?

**Comment by aaj** [comment]
I looked at django's `activate` method, and it doesn't seem to set any session keys. It doesn't even deal with requests:

```python
def activate(timezone):
    """
    Sets the time zone for the current thread.
    The ``timezone`` argument must be an instance of a tzinfo subclass or a
    time zone name. If it is a time zone name, pytz is required.
    """
    if isinstance(timezone, tzinfo):
        _active.value = timezone
    elif isinstance(timezone, six.string_types) and pytz is not None:
        _active.value = pytz.timezone(timezone)
    else:
        raise ValueError("Invalid timezone: %r" % timezone)
```

Maybe, in previous versions of django, it did.

The tz detection still works, it's just going to lookup the request's IP address every time, instead of saving it to session.

**Comment by lucas03** [comment]
Well may be pytz.timezone does that. It is definitely not getting timezone from ip on every request. In middleware it checks if its set or not:
```
tz = request.session.get('django_timezone')
if not tz:
...
```

**Comment by aaj** [comment]
That's what is so strange. It is checking for the value, but I am also checking for it in my view, each request, and it is never set. The timezone gets activated properly, and all works as expected, but that session value is never set to anything when I check it in my views. 

If it's never set, then `if not tz:` is always True, and it will always end up calling `tz = db.time_zone_by_addr(ip)`. 

I might do some more testing. I haven't tried this in like 2 weeks but I'm pretty sure that I was never able to get any value from `request.session.get('django_timezone')`.

**Comment by Miserlou** [comment]
Set explicitly in 0.6.1
